apiVersion: v1
kind: Service
metadata:
  name: api-terrier
  namespace: terrier
spec:
  selector:
    app: api-terrier
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-terrier
  namespace: terrier
  labels:
    app: api-terrier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-terrier
  template:
    metadata:
      labels:
        app: api-terrier
    spec:
      containers:
        - name: api-terrier
          image: ghcr.io/ltorbay/api-terrier-crm:0.0.2
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-terrier.terrier.svc.cluster.local:3306/terrier
            - name: CORS_ALLOWED_ORIGINS_0
              value: https://gites-leterrier.fr/
            - name: CORS_ALLOWED_ORIGINS_1
              value: https://leterrier-gites.fr/
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-username
                  optional: false
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
                  optional: false
            - name: ADMIN_USERS_0_LOGIN
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: user0-login
                  optional: false
            - name: ADMIN_USERS_0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: user0-password
                  optional: false
          ports:
            - containerPort: 8080
          # TODO API logs destination