apiVersion: v1
kind: Service
metadata:
  name: crm-terrier
  namespace: terrier
spec:
  selector:
    app: crm-terrier
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-terrier
  namespace: terrier
  labels:
    app: crm-terrier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-terrier
  template:
    metadata:
      labels:
        app: crm-terrier
    spec:
      containers:
        - name: crm-terrier
          image: ghcr.io/ltorbay/terrier-crm:0.0.6
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/log/nginx
              name: log
      volumes:
        - name: log
          emptyDir: { }