apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: terrier
spec:
  acme:
    email: "louistorbay@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod
    server: "https://acme-v02.api.letsencrypt.org/directory"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  name: nginx-ingress
  namespace: terrier
spec:
  defaultBackend:
    service:
      name: rp-terrier
      port:
        number: 80
  rules:
    - host: gites-leterrier.fr
      http:
        paths:
          - backend:
              service:
                name: rp-terrier
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - gites-leterrier.fr
      secretName: letsencrypt-prod