apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: terrier
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
        log_format  main
                'remote_addr:$remote_addr\t'
                'time_local:$time_local\t'
                'method:$request_method\t'
                'uri:$request_uri\t'
                'host:$host\t'
                'status:$status\t'
                'bytes_sent:$body_bytes_sent\t'
                'referer:$http_referer\t'
                'useragent:$http_user_agent\t'
                'forwardedfor:$http_x_forwarded_for\t'
                'request_time:$request_time';
        access_log	/var/log/nginx/access.log main;
  
        server {
          listen 80 default_server;
          listen [::]:80 default_server;
          server_name _;
          return 301 https://$host$request_uri;
        }
  
        server {
            listen 443 ssl default_server;
            listen [::]:443 ssl default_server;
            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;
  
            server_name  terrier-rp;
            location /api {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_redirect   off;
                proxy_pass       http://api-terrier.terrier.svc.cluster.local:8080;
                rewrite /api/(.*) /$1  break;
            }
            location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_pass       http://crm-terrier.terrier.svc.cluster.local:80;
            }
        }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: rp-terrier
  namespace: terrier
  labels:
    app: rp-terrier
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
  selector:
    app: rp-terrier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rp-terrier
  namespace: terrier
  labels:
    app: rp-terrier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rp-terrier
  template:
    metadata:
      labels:
        app: rp-terrier
    spec:
      containers:
        - name: rp-terrier
          image: nginx:1.22.0
          volumeMounts:
            - mountPath: /etc/nginx
              readOnly: true
              name: nginx-conf
            - mountPath: /etc/nginx/ssl
              name: secret-volume
            - mountPath: /var/log/nginx
              name: log
          ports:
            - containerPort: 80
              name: http-port
            - containerPort: 443
              name: https-port
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: secret-volume
          secret:
            secretName: tls-cert-secret
        - name: log
          emptyDir: {}
